### PR TITLE
Some small changes to missing auras highlights for consistency

### PR DESCRIPTION
**Pull request by Rainrider**
With your changes you leave two ways to have a flash highlight for missing auras:
  1. Select `Show flash`
  2. Select `Invert border` and check `Show flash instead`

May I offer a fix for that? Do you think it keeps consistency with the current behavior of `Show flash instead`?

### CODE REVIEW

**Comment by myth384** [comment]
There is one difference in my pull request between the two, though. With `Show flash` selected, a coloured highlight is shown when a (de)buff is active. This is not the case when `Invert border` is selected and `Show flash instead` is checked.
Personally, I don't mind your change, because I won't be using the combination of `Inverted` + `Show flash instead`. I'm even wondering if `Show flash instead` still has a use... It's up to you to decide.

When we're going to change the wording of `Invert border` to `Show border`, we should change the variable `invert` to `show` as well for consistency.

**Comment by myth384** [comment]
Correction; I actually do have a use for `Show flash instead` on my monk. I'm using it to flash up Touch of Death when the buff Death Note pops up.

**Comment by Rainrider** [comment]
Yes, there is use for `Show flash instead`, that is out of question. I also thought about actually inverting the border between "good" and "bad" but there is some ambiguity to it: one could consider the presence of their own debuffs on an enemy a good thing, but ABA generally shows the bad border for debuffs. So inverting would then show the good border if the debuff is not found, which could be a signal to the user that no action is required. Also, it is somewhat inconsistent that the user can change the highlight type for missing auras but is limited to `Show flash instead` for present ones. I'll probably leave that be for now though.

Would you please accept my pull request then? I'm not sure if that is the right way to collaborate on pull requests in github, but I think I could then merge your PR to ABA with my changes included.

**Comment by myth384** [comment]
Then we have a consensus. ;-)
Do you want me to rebase all commits in my fork into one commit before pulling it to Adirelle's repository? That will keep the history clean.

I will also rename the `invert` dropdown list option to `show` as suggested earlier.

**Pull request merged**
